---
- name: Ensure PHP configuration directories exist.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    follow: true
  with_items: "{{ php_xhprof_config_dirs }}"

- name: Copy XHProf INI into various other conf folders.
  template:
    src: xhprof.ini.j2
    dest: "{{ item }}/{{ php_xhprof_config_filename }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ php_xhprof_config_dirs }}"
  notify: restart webserver
